// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	SoftCreate(ctx context.Context, in *AuthMessage, opts ...grpc.CallOption) (*AuthMessage, error)
	HardCreate(ctx context.Context, in *AuthMessage, opts ...grpc.CallOption) (*AuthMessage, error)
	Get(ctx context.Context, in *AuthMessage, opts ...grpc.CallOption) (*AuthMessage, error)
	Extend(ctx context.Context, in *AuthMessage, opts ...grpc.CallOption) (*AuthMessage, error)
	Delete(ctx context.Context, in *AuthMessage, opts ...grpc.CallOption) (*AuthMessage, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SoftCreate(ctx context.Context, in *AuthMessage, opts ...grpc.CallOption) (*AuthMessage, error) {
	out := new(AuthMessage)
	err := c.cc.Invoke(ctx, "/auth.AuthService/SoftCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) HardCreate(ctx context.Context, in *AuthMessage, opts ...grpc.CallOption) (*AuthMessage, error) {
	out := new(AuthMessage)
	err := c.cc.Invoke(ctx, "/auth.AuthService/HardCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Get(ctx context.Context, in *AuthMessage, opts ...grpc.CallOption) (*AuthMessage, error) {
	out := new(AuthMessage)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Extend(ctx context.Context, in *AuthMessage, opts ...grpc.CallOption) (*AuthMessage, error) {
	out := new(AuthMessage)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Extend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Delete(ctx context.Context, in *AuthMessage, opts ...grpc.CallOption) (*AuthMessage, error) {
	out := new(AuthMessage)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	SoftCreate(context.Context, *AuthMessage) (*AuthMessage, error)
	HardCreate(context.Context, *AuthMessage) (*AuthMessage, error)
	Get(context.Context, *AuthMessage) (*AuthMessage, error)
	Extend(context.Context, *AuthMessage) (*AuthMessage, error)
	Delete(context.Context, *AuthMessage) (*AuthMessage, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) SoftCreate(context.Context, *AuthMessage) (*AuthMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SoftCreate not implemented")
}
func (UnimplementedAuthServiceServer) HardCreate(context.Context, *AuthMessage) (*AuthMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HardCreate not implemented")
}
func (UnimplementedAuthServiceServer) Get(context.Context, *AuthMessage) (*AuthMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAuthServiceServer) Extend(context.Context, *AuthMessage) (*AuthMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Extend not implemented")
}
func (UnimplementedAuthServiceServer) Delete(context.Context, *AuthMessage) (*AuthMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_SoftCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SoftCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/SoftCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SoftCreate(ctx, req.(*AuthMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_HardCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).HardCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/HardCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).HardCreate(ctx, req.(*AuthMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Get(ctx, req.(*AuthMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Extend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Extend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Extend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Extend(ctx, req.(*AuthMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Delete(ctx, req.(*AuthMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SoftCreate",
			Handler:    _AuthService_SoftCreate_Handler,
		},
		{
			MethodName: "HardCreate",
			Handler:    _AuthService_HardCreate_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AuthService_Get_Handler,
		},
		{
			MethodName: "Extend",
			Handler:    _AuthService_Extend_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AuthService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_service.proto",
}
